// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

/**
 * `.env.local` AVANT `.env`, et non la convention `import "dotenv/config"`.
 *
 * C'est `.env.local` que lit Next et où vivent les identifiants de ce projet ;
 * `.env` n'y existe pas. La convention générée par Prisma ne charge QUE `.env`,
 * si bien que `pnpm db:push` échouait sur « The datasource.url property is
 * required in your Prisma config file » : la variable n'était jamais lue, et
 * l'erreur accusait ce fichier plutôt que l'environnement.
 *
 * `dotenv` n'écrase pas une variable déjà posée : l'ordre reproduit donc la
 * précédence de Next, et un `DATABASE_URL` fourni par l'environnement —
 * intégration continue, plateforme d'hébergement — l'emporte sur les deux
 * fichiers. Même dispositif que les tests d'intégration
 * (cf. scripts/tests/docs-query-integration.test.ts).
 */
config({ path: ".env.local", quiet: true });
config({ quiet: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
