/**
 * Fiches de référence des 26 provinces — état initial du module « Provinces »
 * (cf. lib/provinces/bootstrap.ts), et repli de la page publique tant qu'aucune
 * fiche n'est publiée en base.
 *
 * ⚠️ Données PUBLIQUES, pas données du projet. Chaque fiche cite ses sources :
 *   · superficie et population : INS RDC, projection au 1er juillet 2020
 *     (republiée par citypopulation.de, qui en signale la faible fiabilité) —
 *     seule série couvrant les 26 provinces de façon homogène ;
 *   · territoires : CAID 2018 ; villes : annuaire INS 2015, plus Baraka et
 *     Uvira (2018) — une ville créée depuis peut manquer ;
 *   · gouverneur : renseigné SEULEMENT quand une source datée de 2025-2026 le
 *     confirme, avec cette date ; sinon laissé vide, et la ligne ne s'affiche
 *     pas. Les gouverneurs changent : la console fait foi.
 *   · langues : indicatives (français + langues véhiculaires dominantes).
 *
 * Fichier GÉNÉRÉ depuis la recherche documentaire du 6 octobre 2026 ; à
 * corriger ensuite dans la console, pas ici.
 */
import type { ProvinceFicheSeed } from "@/content/types";

export const provincesFiches: ProvinceFicheSeed[] = [
  {
    slug: "kinshasa",
    chefLieu: "Kinshasa",
    superficieKm2: 9965,
    population: 14565700,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: null,
    communes: 24,
    villes: ["Kinshasa"],
    gouverneur: "Daniel Bumba Lubaki",
    viceGouverneur: "Eddy Iyeli Molangi",
    gouverneurDate: "2026-09-22",
    gouverneurSource: "https://www.radiookapi.net/2026/09/22/actualite/politique/marche-de-ludps-kinshasa-daniel-bumba-appelle-au-respect-de",
    langues: ["français", "lingala"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo", "https://www.radiookapi.net/2026/09/22/actualite/politique/marche-de-ludps-kinshasa-daniel-bumba-appelle-au-respect-de"],
    description: { fr: "Ville-province et capitale du pays, Kinshasa s'étend sur la rive sud du fleuve Congo, face à Brazzaville, et concentre les institutions nationales ainsi qu'une large part de l'activité administrative, commerciale et de services.", en: "A city-province and the national capital, Kinshasa lies on the south bank of the Congo River opposite Brazzaville and hosts the national institutions and a large share of administrative, commercial and service activity." },
    administration: null,
  },
  {
    slug: "kongo-central",
    chefLieu: "Matadi",
    superficieKm2: 53920,
    population: 6838500,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: 10,
    communes: null,
    villes: ["Matadi", "Boma"],
    gouverneur: "Grâce Nkuanga Masuangi Bilolo",
    viceGouverneur: null,
    gouverneurDate: "2026-09-12",
    gouverneurSource: "https://www.congoquotidien.com/2026/09/12/gouverneur-kongo-central-assemblee-provinciale/",
    langues: ["français", "kikongo"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo", "https://www.congoquotidien.com/2026/09/12/gouverneur-kongo-central-assemblee-provinciale/"],
    description: { fr: "Seule province du pays ouverte sur l'océan Atlantique, le Kongo Central est traversé par le bas fleuve Congo et le corridor routier et ferroviaire reliant Kinshasa aux ports de Matadi et de Boma.", en: "The only province with an Atlantic coastline, Kongo Central is crossed by the lower Congo River and by the road and rail corridor linking Kinshasa to the ports of Matadi and Boma." },
    administration: null,
  },
  {
    slug: "kwilu",
    chefLieu: "Bandundu",
    superficieKm2: 78533,
    population: 6682300,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: 5,
    communes: null,
    villes: ["Bandundu", "Kikwit"],
    gouverneur: "Philippe Akamituna Ndolo",
    viceGouverneur: null,
    gouverneurDate: "2026-09-24",
    gouverneurSource: "https://rtnc.cd/kwilu-akamituna-ndolo-explore-avec-la-cadeco-les-possibilites-de-financer-les-acteurs-economiques/",
    langues: ["français", "kikongo", "lingala"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo", "https://rtnc.cd/kwilu-akamituna-ndolo-explore-avec-la-cadeco-les-possibilites-de-financer-les-acteurs-economiques/"],
    description: { fr: "Située dans l'ouest du pays et arrosée par les rivières Kwilu et Kasaï, la province du Kwilu a une économie principalement agricole ; elle compte deux villes, Bandundu, son chef-lieu, et Kikwit.", en: "Located in the west of the country and drained by the Kwilu and Kasai rivers, Kwilu province has a mainly agricultural economy; it has two cities, Bandundu, its capital, and Kikwit." },
    administration: null,
  },
  {
    slug: "kwango",
    chefLieu: "Kenge",
    superficieKm2: 89974,
    population: 2618700,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: 5,
    communes: null,
    villes: ["Kenge"],
    gouverneur: "Willy Bitwisila Lusundji",
    viceGouverneur: null,
    gouverneurDate: "2026-09-30",
    gouverneurSource: "https://rtnc.cd/kwango-lassemblee-provinciale-ouvre-sa-session-de-septembre-sous-le-signe-de-responsabilite/",
    langues: ["français", "kikongo"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo", "https://rtnc.cd/kwango-lassemblee-provinciale-ouvre-sa-session-de-septembre-sous-le-signe-de-responsabilite/"],
    description: { fr: "Province du sud-ouest frontalière de l'Angola, le Kwango est un territoire de plateaux et de savanes traversé par la rivière Kwango, où dominent l'agriculture et le petit élevage.", en: "A south-western province bordering Angola, Kwango is a land of plateaus and savannah crossed by the Kwango River, where agriculture and small-scale livestock farming predominate." },
    administration: null,
  },
  {
    slug: "mai-ndombe",
    chefLieu: "Inongo",
    superficieKm2: 127243,
    population: 2254100,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: 8,
    communes: null,
    villes: ["Inongo"],
    gouverneur: "Lebon Nkoso Kevani",
    viceGouverneur: null,
    gouverneurDate: "2026-09-01",
    gouverneurSource: "https://www.congoquotidien.com/2026/09/01/mai-ndombe-remaniement-gouvernemental-seule-femme-ministre/",
    langues: ["français", "lingala", "kikongo"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo", "https://www.congoquotidien.com/2026/09/01/mai-ndombe-remaniement-gouvernemental-seule-femme-ministre/"],
    description: { fr: "Province de l'ouest bordée par les fleuves Congo et Kasaï et centrée sur le lac Mai-Ndombe, le Mai-Ndombe associe forêts, savanes et activités de pêche, d'agriculture et d'exploitation forestière.", en: "A western province bounded by the Congo and Kasai rivers and centred on Lake Mai-Ndombe, Mai-Ndombe combines forest and savannah with fishing, agriculture and forestry." },
    administration: null,
  },
  {
    slug: "equateur",
    chefLieu: "Mbandaka",
    superficieKm2: 103902,
    population: 1856000,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: 7,
    communes: null,
    villes: ["Mbandaka"],
    gouverneur: "Dieudonné Bobo Boloko Bolumbu",
    viceGouverneur: null,
    gouverneurDate: "2026-09-12",
    gouverneurSource: "https://globalnewsrdc.net/societe/ouverture-de-la-10e-session-du-comite-de-pilotage-du-projet-pirred-equateur-le-gouverneur-bobo-boloko-apprecie-les-resultats-palpables-et-plaide-pour-lextension-du-projet-en-faveur-des-comm/",
    langues: ["français", "lingala"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo", "https://globalnewsrdc.net/societe/ouverture-de-la-10e-session-du-comite-de-pilotage-du-projet-pirred-equateur-le-gouverneur-bobo-boloko-apprecie-les-resultats-palpables-et-plaide-pour-lextension-du-projet-en-faveur-des-comm/"],
    description: { fr: "Traversée par l'équateur et longée par le fleuve Congo, la province de l'Équateur est couverte en grande partie de forêts et de zones humides ; son chef-lieu Mbandaka est un port fluvial.", en: "Crossed by the equator and bordered by the Congo River, Équateur province is largely covered by forests and wetlands; its capital Mbandaka is a river port." },
    administration: null,
  },
  {
    slug: "sud-ubangi",
    chefLieu: "Gemena",
    superficieKm2: 51648,
    population: 2987100,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: 4,
    communes: null,
    villes: ["Gemena", "Zongo"],
    gouverneur: "Jean-René Galekwa Vundawe (a.i.)",
    viceGouverneur: null,
    gouverneurDate: "2026-09-02",
    gouverneurSource: "https://www.congoquotidien.com/2026/09/02/sud-ubangi-rn6-chantier-desenclaver-province/",
    langues: ["français", "lingala"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo", "https://www.congoquotidien.com/2026/09/02/sud-ubangi-rn6-chantier-desenclaver-province/"],
    description: { fr: "Province du nord-ouest bordée par la rivière Oubangui, frontière avec la République centrafricaine et la République du Congo, le Sud-Ubangi a une économie surtout agricole.", en: "A north-western province bordered by the Ubangi River, which forms the border with the Central African Republic and the Republic of the Congo, Sud-Ubangi has a mainly agricultural economy." },
    administration: {"fr": "Le vice-gouverneur assure l'intérim depuis le 26 février 2026.", "en": "The vice-governor has been acting governor since 26 February 2026."},
  },
  {
    slug: "nord-ubangi",
    chefLieu: "Gbadolite",
    superficieKm2: 56644,
    population: 1542500,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: 4,
    communes: null,
    villes: ["Gbadolite"],
    gouverneur: "Jean-Bosco Kotongo Anfio Bato",
    viceGouverneur: null,
    gouverneurDate: "2026-06-23",
    gouverneurSource: "https://rtnc.cd/nord-ubangi-jean-bosco-kotongo-lance-les-epreuves-de-lexamen-detat-2026/",
    langues: ["français", "lingala"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo", "https://rtnc.cd/nord-ubangi-jean-bosco-kotongo-lance-les-epreuves-de-lexamen-detat-2026/"],
    description: { fr: "Province du nord frontalière de la République centrafricaine le long de l'Oubangui, le Nord-Ubangi a pour chef-lieu Gbadolite et vit principalement de l'agriculture.", en: "A northern province bordering the Central African Republic along the Ubangi River, Nord-Ubangi has Gbadolite as its capital and relies mainly on agriculture." },
    administration: null,
  },
  {
    slug: "mongala",
    chefLieu: "Lisala",
    superficieKm2: 58141,
    population: 2114100,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: 3,
    communes: null,
    villes: ["Lisala"],
    gouverneur: "Jean-Collins Makaka Pap'ekaka",
    viceGouverneur: "Cédric Ayakakoma",
    gouverneurDate: "2026-10-01",
    gouverneurSource: "https://rtnc.cd/mongala-vers-une-solution-durable-dans-le-conflit-communautaire-entre-makanza-et-bongandanga/",
    langues: ["français", "lingala"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo", "https://rtnc.cd/mongala-vers-une-solution-durable-dans-le-conflit-communautaire-entre-makanza-et-bongandanga/"],
    description: { fr: "Province du nord traversée par le fleuve Congo, la Mongala compte des ports fluviaux à Lisala et Bumba et une économie fondée sur l'agriculture et le commerce fluvial.", en: "A northern province crossed by the Congo River, Mongala has river ports at Lisala and Bumba and an economy based on agriculture and river trade." },
    administration: null,
  },
  {
    slug: "bas-uele",
    chefLieu: "Buta",
    superficieKm2: 148331,
    population: 1369600,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: 6,
    communes: null,
    villes: ["Buta"],
    gouverneur: "Mike-David Mokeni Amisi",
    viceGouverneur: null,
    gouverneurDate: "2026-09-30",
    gouverneurSource: "https://www.reporter.cd/bas-uele-le-gouverneur-lance-a-buta-un-premier-projet-de-betonnage-pour-moderniser-la-voirie/",
    langues: ["français", "lingala"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo", "https://www.reporter.cd/bas-uele-le-gouverneur-lance-a-buta-un-premier-projet-de-betonnage-pour-moderniser-la-voirie/"],
    description: { fr: "Province du nord frontalière de la République centrafricaine, le Bas-Uele est une région de forêts et de savanes arrosée par la rivière Uele, peu densément peuplée.", en: "A northern province bordering the Central African Republic, Bas-Uele is a sparsely populated area of forest and savannah drained by the Uele River." },
    administration: null,
  },
  {
    slug: "haut-uele",
    chefLieu: "Isiro",
    superficieKm2: 89683,
    population: 2242500,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: 6,
    communes: null,
    villes: ["Isiro"],
    gouverneur: "Jean Bakomito Gambu",
    viceGouverneur: "Christophe Dara Matata",
    gouverneurDate: "2026-08-21",
    gouverneurSource: "https://www.congoquotidien.com/2026/08/21/haut-uele-gouverneur-demantele-barriere-irreguliere/",
    langues: ["français", "lingala", "swahili"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo", "https://www.congoquotidien.com/2026/08/21/haut-uele-gouverneur-demantele-barriere-irreguliere/"],
    description: { fr: "Province du nord-est frontalière du Soudan du Sud et de la République centrafricaine, le Haut-Uele abrite le parc national de la Garamba et des activités d'extraction aurifère.", en: "A north-eastern province bordering South Sudan and the Central African Republic, Haut-Uele is home to Garamba National Park and to gold mining activities." },
    administration: null,
  },
  {
    slug: "ituri",
    chefLieu: "Bunia",
    superficieKm2: 65658,
    population: 4392200,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: 5,
    communes: null,
    villes: ["Bunia"],
    gouverneur: "Général-major Gaby Kasongo Mulumba Batoka",
    viceGouverneur: null,
    gouverneurDate: "2026-07-25",
    gouverneurSource: "https://actualite.cd/2026/06/05/ituri-un-nouveau-gouverneur-militaire-en-remplacement-du-general-luboya-nkashama",
    langues: ["français", "swahili", "lingala"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo", "https://actualite.cd/2026/06/05/ituri-un-nouveau-gouverneur-militaire-en-remplacement-du-general-luboya-nkashama"],
    description: { fr: "Province du nord-est frontalière de l'Ouganda et du Soudan du Sud et bordée par le lac Albert, l'Ituri associe hauts plateaux agricoles, forêt et gisements d'or.", en: "A north-eastern province bordering Uganda and South Sudan and bounded by Lake Albert, Ituri combines farming highlands, forest and gold deposits." },
    administration: {"fr": "Province sous état de siège depuis mai 2021, administrée par un gouverneur militaire.", "en": "Under a state of siege since May 2021, administered by a military governor."},
  },
  {
    slug: "tshopo",
    chefLieu: "Kisangani",
    superficieKm2: 199567,
    population: 2829700,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: 7,
    communes: null,
    villes: ["Kisangani"],
    gouverneur: "Paulin Lendongolia Lebabonga",
    viceGouverneur: "Didier Lomoyo Iteku",
    gouverneurDate: "2026-09-14",
    gouverneurSource: "https://www.radiookapi.net/2026/09/14/actualite/politique/tshopo-la-marche-de-lopposition-interdite-pour-raisons-sanitaires",
    langues: ["français", "swahili", "lingala"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo", "https://www.radiookapi.net/2026/09/14/actualite/politique/tshopo-la-marche-de-lopposition-interdite-pour-raisons-sanitaires"],
    description: { fr: "Province la plus étendue du pays, la Tshopo est largement forestière et organisée autour du fleuve Congo ; son chef-lieu Kisangani est un carrefour fluvial et commercial.", en: "The country's largest province by area, Tshopo is largely forested and organised around the Congo River; its capital Kisangani is a river and trade hub." },
    administration: null,
  },
  {
    slug: "tshuapa",
    chefLieu: "Boende",
    superficieKm2: 132957,
    population: 1944500,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: 6,
    communes: null,
    villes: ["Boende"],
    gouverneur: null,
    viceGouverneur: null,
    gouverneurDate: null,
    gouverneurSource: null,
    langues: ["français", "lingala"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo"],
    description: { fr: "Province du centre-nord du bassin du Congo, la Tshuapa est couverte de forêt équatoriale et dépend principalement des rivières pour ses transports et des activités agricoles.", en: "A province in the north-central Congo Basin, Tshuapa is covered by equatorial forest and relies mainly on rivers for transport and on agriculture." },
    administration: null,
  },
  {
    slug: "sankuru",
    chefLieu: "Lusambo",
    superficieKm2: 104331,
    population: 2593400,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: 6,
    communes: null,
    villes: ["Lusambo"],
    gouverneur: "Jules Lodi Emongo",
    viceGouverneur: "Charles Motomuke Yanape",
    gouverneurDate: "2026-07-01",
    gouverneurSource: "https://rtnc.cd/sankuru-jules-lodi-et-charles-motomuke-investis-par-ordonnance-presidentielle/",
    langues: ["français", "tetela", "tshiluba"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo", "https://rtnc.cd/sankuru-jules-lodi-et-charles-motomuke-investis-par-ordonnance-presidentielle/"],
    description: { fr: "Province du centre du pays arrosée par la rivière Sankuru, le Sankuru est une région de forêts et de savanes à dominante agricole, dont le chef-lieu est Lusambo.", en: "A central province drained by the Sankuru River, Sankuru is a mainly agricultural area of forest and savannah whose capital is Lusambo." },
    administration: null,
  },
  {
    slug: "kasai",
    chefLieu: "Tshikapa",
    superficieKm2: 95631,
    population: 3417000,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: 5,
    communes: null,
    villes: ["Tshikapa"],
    gouverneur: "Crispin Mukendi Bukasa",
    viceGouverneur: null,
    gouverneurDate: "2026-09-13",
    gouverneurSource: "https://www.congo-press.com/provinces/kasai-denise-nyakeru-tshisekedi-attendue-a-tshikapa-le-17-septembre/",
    langues: ["français", "tshiluba"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo", "https://www.congo-press.com/provinces/kasai-denise-nyakeru-tshisekedi-attendue-a-tshikapa-le-17-septembre/"],
    description: { fr: "Province du centre-sud frontalière de l'Angola, le Kasaï est connu pour ses gisements de diamants alluviaux, exploités notamment autour de Tshikapa, ainsi que pour son agriculture.", en: "A south-central province bordering Angola, Kasaï is known for its alluvial diamond deposits, mined notably around Tshikapa, and for agriculture." },
    administration: null,
  },
  {
    slug: "kasai-central",
    chefLieu: "Kananga",
    superficieKm2: 59500,
    population: 4045300,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: 5,
    communes: null,
    villes: ["Kananga"],
    gouverneur: "Joseph-Moïse Kambulu N'Konko",
    viceGouverneur: null,
    gouverneurDate: "2026-09-18",
    gouverneurSource: "https://rtnc.cd/kasai-central-joseph-moise-kambulu-lance-la-construction-dun-immeuble-pour-les-inspections-agricoles/",
    langues: ["français", "tshiluba"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo", "https://rtnc.cd/kasai-central-joseph-moise-kambulu-lance-la-construction-dun-immeuble-pour-les-inspections-agricoles/"],
    description: { fr: "Province du centre du pays, le Kasaï Central a pour chef-lieu Kananga, nœud ferroviaire sur la ligne reliant le Katanga à Ilebo, et une économie surtout agricole.", en: "A central province, Kasaï Central has Kananga as its capital, a rail junction on the line linking Katanga to Ilebo, and a mainly agricultural economy." },
    administration: null,
  },
  {
    slug: "kasai-oriental",
    chefLieu: "Mbuji-Mayi",
    superficieKm2: 9545,
    population: 3864300,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: 5,
    communes: null,
    villes: ["Mbuji-Mayi"],
    gouverneur: "Jean-Paul Mbwebwa Kapo",
    viceGouverneur: null,
    gouverneurDate: "2026-10-06",
    gouverneurSource: "https://www.mediacongo.net/article-actualite-168096_grand_kasai_une_conference_sur_le_developpement_regional_s_ouvre_a_mbuji_mayi.html",
    langues: ["français", "tshiluba"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo", "https://www.mediacongo.net/article-actualite-168096_grand_kasai_une_conference_sur_le_developpement_regional_s_ouvre_a_mbuji_mayi.html"],
    description: { fr: "Plus petite province du pays par la superficie selon l'INS, le Kasaï Oriental est densément peuplé et centré sur Mbuji-Mayi, ville dont l'économie est liée à l'extraction de diamants.", en: "The smallest province by area according to INS figures, Kasaï Oriental is densely populated and centred on Mbuji-Mayi, a city whose economy is linked to diamond mining." },
    administration: null,
  },
  {
    slug: "lomami",
    chefLieu: "Kabinda",
    superficieKm2: 56426,
    population: 3001900,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: 5,
    communes: null,
    villes: ["Kabinda", "Mwene-Ditu"],
    gouverneur: "Iron-Van Kalombo Musoko",
    viceGouverneur: null,
    gouverneurDate: "2026-09-29",
    gouverneurSource: "https://www.congoquotidien.com/2026/09/29/frais-scolaires-lomami-iron/",
    langues: ["français", "tshiluba", "swahili"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo", "https://www.congoquotidien.com/2026/09/29/frais-scolaires-lomami-iron/"],
    description: { fr: "Province du centre du pays traversée par la voie ferrée Lubumbashi-Ilebo, la Lomami compte deux villes, Kabinda et Mwene-Ditu, et une économie principalement agricole.", en: "A central province crossed by the Lubumbashi-Ilebo railway, Lomami has two cities, Kabinda and Mwene-Ditu, and a mainly agricultural economy." },
    administration: null,
  },
  {
    slug: "maniema",
    chefLieu: "Kindu",
    superficieKm2: 132250,
    population: 2856300,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: 7,
    communes: null,
    villes: ["Kindu"],
    gouverneur: "Moïse Mussa Kabwankubi",
    viceGouverneur: null,
    gouverneurDate: "2026-09-30",
    gouverneurSource: "https://rtnc.cd/maniema-ouverture-de-la-session-ordinaire-de-septembre-a-lassemblee-provinciale/",
    langues: ["français", "swahili"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo", "https://rtnc.cd/maniema-ouverture-de-la-session-ordinaire-de-septembre-a-lassemblee-provinciale/"],
    description: { fr: "Province de l'est traversée par le fleuve Congo (Lualaba), le Maniema associe forêts, agriculture et exploitation minière artisanale d'or et de cassitérite.", en: "An eastern province crossed by the Congo (Lualaba) River, Maniema combines forest, agriculture and artisanal mining of gold and cassiterite." },
    administration: null,
  },
  {
    slug: "nord-kivu",
    chefLieu: "Goma",
    superficieKm2: 59483,
    population: 8147400,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: 6,
    communes: null,
    villes: ["Goma", "Beni", "Butembo"],
    gouverneur: "Général-major Évariste Kakule Somo",
    viceGouverneur: null,
    gouverneurDate: "2026-08-18",
    gouverneurSource: "https://kivuavenir.com/nord-kivu-ludps-reclame-le-depart-du-gouverneur-militaire-evariste-somo-kakule/",
    langues: ["français", "swahili"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo", "https://kivuavenir.com/nord-kivu-ludps-reclame-le-depart-du-gouverneur-militaire-evariste-somo-kakule/"],
    description: { fr: "Province de l'est frontalière de l'Ouganda et du Rwanda, le Nord-Kivu s'étend entre le lac Kivu et le lac Édouard, abrite le parc national des Virunga et possède des terres volcaniques agricoles.", en: "An eastern province bordering Uganda and Rwanda, Nord-Kivu stretches between Lake Kivu and Lake Edward, is home to Virunga National Park and has volcanic farmland." },
    administration: {"fr": "Province sous état de siège depuis mai 2021, administrée par un gouverneur militaire. Les autorités provinciales siègent à Beni depuis janvier 2025.", "en": "Under a state of siege since May 2021, administered by a military governor. Provincial authorities have sat in Beni since January 2025."},
  },
  {
    slug: "sud-kivu",
    chefLieu: "Bukavu",
    superficieKm2: 64791,
    population: 7066400,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: 8,
    communes: null,
    villes: ["Bukavu", "Uvira", "Baraka"],
    gouverneur: "Jean-Jacques Purusi Sadiki",
    viceGouverneur: null,
    gouverneurDate: "2026-09-29",
    gouverneurSource: "https://kivuavenir.com/sud-kivu-purusi-multiplie-les-consultations-a-uvira-avant-la-rentree-parlementaire/",
    langues: ["français", "swahili"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo", "https://kivuavenir.com/sud-kivu-purusi-multiplie-les-consultations-a-uvira-avant-la-rentree-parlementaire/"],
    description: { fr: "Province de l'est frontalière du Rwanda, du Burundi et de la Tanzanie (par le lac Tanganyika), le Sud-Kivu s'étend du lac Kivu au lac Tanganyika et associe agriculture et exploitation minière.", en: "An eastern province bordering Rwanda, Burundi and Tanzania (across Lake Tanganyika), Sud-Kivu stretches from Lake Kivu to Lake Tanganyika and combines agriculture and mining." },
    administration: {"fr": "Le gouvernement provincial exerce depuis Uvira depuis février 2025.", "en": "The provincial government has operated from Uvira since February 2025."},
  },
  {
    slug: "tanganyika",
    chefLieu: "Kalemie",
    superficieKm2: 134940,
    population: 3792200,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: 6,
    communes: null,
    villes: ["Kalemie"],
    gouverneur: "Christian Kitungwa Muteba",
    viceGouverneur: null,
    gouverneurDate: "2026-09-19",
    gouverneurSource: "https://rtnc.cd/tanganyika-lunion-sacree-installe-ses-structures-provinciales-a-kalemie/",
    langues: ["français", "swahili"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo", "https://rtnc.cd/tanganyika-lunion-sacree-installe-ses-structures-provinciales-a-kalemie/"],
    description: { fr: "Province du sud-est bordée par le lac Tanganyika, le Tanganyika a pour chef-lieu le port lacustre de Kalemie et abrite notamment des gisements de lithium et d'étain à Manono.", en: "A south-eastern province bordered by Lake Tanganyika, Tanganyika has the lake port of Kalemie as its capital and contains lithium and tin deposits, notably at Manono." },
    administration: null,
  },
  {
    slug: "haut-lomami",
    chefLieu: "Kamina",
    superficieKm2: 108204,
    population: 3662800,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: 5,
    communes: null,
    villes: ["Kamina"],
    gouverneur: "Marmont Banza Mulume",
    viceGouverneur: null,
    gouverneurDate: "2026-09-23",
    gouverneurSource: "https://www.mediacongo.net/article-actualite-167710_haut_lomami_le_gouverneur_marmont_banza_mulume_reamenage_son_gouvernement.html",
    langues: ["français", "swahili"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo", "https://www.mediacongo.net/article-actualite-167710_haut_lomami_le_gouverneur_marmont_banza_mulume_reamenage_son_gouvernement.html"],
    description: { fr: "Province du sud du pays traversée par le fleuve Lualaba et la rivière Lomami, le Haut-Lomami a pour chef-lieu Kamina, nœud ferroviaire, et une économie principalement agricole.", en: "A southern province crossed by the Lualaba and Lomami rivers, Haut-Lomami has Kamina, a rail junction, as its capital and a mainly agricultural economy." },
    administration: null,
  },
  {
    slug: "lualaba",
    chefLieu: "Kolwezi",
    superficieKm2: 121308,
    population: 3183300,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: 5,
    communes: null,
    villes: ["Kolwezi"],
    gouverneur: "Fifi Masuka Saini",
    viceGouverneur: null,
    gouverneurDate: "2026-07-08",
    gouverneurSource: "https://beto.cd/kolwezi-fashion-week-2026-lualaba-mode-congolaise/",
    langues: ["français", "swahili"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo", "https://beto.cd/kolwezi-fashion-week-2026-lualaba-mode-congolaise/"],
    description: { fr: "Province du sud frontalière de l'Angola et de la Zambie, le Lualaba fait partie de la ceinture cuprifère et concentre une part importante de la production de cuivre et de cobalt du pays autour de Kolwezi.", en: "A southern province bordering Angola and Zambia, Lualaba is part of the Copperbelt and accounts for a significant share of the country's copper and cobalt production around Kolwezi." },
    administration: null,
  },
  {
    slug: "haut-katanga",
    chefLieu: "Lubumbashi",
    superficieKm2: 132425,
    population: 5718800,
    populationAnnee: 2020,
    populationSource: "INS RDC, projection au 1er juillet 2020",
    territoires: 6,
    communes: null,
    villes: ["Lubumbashi", "Likasi"],
    gouverneur: "Martin Kazembe Shula (a.i.)",
    viceGouverneur: null,
    gouverneurDate: "2026-09-20",
    gouverneurSource: "https://actualite.cd/2026/09/20/haut-katanga-apres-plus-dune-annee-kinshasa-jacques-kyabula-retrouve-lubumbashi-et-sa",
    langues: ["français", "swahili"],
    sources: ["https://www.citypopulation.de/en/drcongo/cities/", "https://fr.wikipedia.org/wiki/Territoire_(r%C3%A9publique_d%C3%A9mocratique_du_Congo)", "https://fr.wikipedia.org/wiki/Liste_des_villes_de_la_r%C3%A9publique_d%C3%A9mocratique_du_Congo", "https://actualite.cd/2026/09/20/haut-katanga-apres-plus-dune-annee-kinshasa-jacques-kyabula-retrouve-lubumbashi-et-sa"],
    description: { fr: "Province du sud-est frontalière de la Zambie, le Haut-Katanga fait partie de la ceinture cuprifère ; son chef-lieu Lubumbashi est un centre minier, industriel et commercial.", en: "A south-eastern province bordering Zambia, Haut-Katanga is part of the Copperbelt; its capital Lubumbashi is a mining, industrial and commercial centre." },
    administration: {"fr": "Le vice-gouverneur assure l'intérim depuis juillet 2025.", "en": "The vice-governor has been acting governor since July 2025."},
  },
];
